In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('mpg.csv')

In [4]:
df # value_counts() .unique()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [7]:
df.groupby('model_year').mean()#['mpg']

model_year
70    17.689655
71    21.250000
72    18.714286
73    17.100000
74    22.703704
75    20.266667
76    21.573529
77    23.375000
78    24.061111
79    25.093103
80    33.696552
81    30.334483
82    31.709677
Name: mpg, dtype: float64

In [12]:
df.groupby(['model_year', 'cylinders']).mean().index

MultiIndex([(70, 4),
            (70, 6),
            (70, 8),
            (71, 4),
            (71, 6),
            (71, 8),
            (72, 3),
            (72, 4),
            (72, 8),
            (73, 3),
            (73, 4),
            (73, 6),
            (73, 8),
            (74, 4),
            (74, 6),
            (74, 8),
            (75, 4),
            (75, 6),
            (75, 8),
            (76, 4),
            (76, 6),
            (76, 8),
            (77, 3),
            (77, 4),
            (77, 6),
            (77, 8),
            (78, 4),
            (78, 5),
            (78, 6),
            (78, 8),
            (79, 4),
            (79, 5),
            (79, 6),
            (79, 8),
            (80, 3),
            (80, 4),
            (80, 5),
            (80, 6),
            (81, 4),
            (81, 6),
            (81, 8),
            (82, 4),
            (82, 6)],
           names=['model_year', 'cylinders'])

In [14]:
df.groupby('model_year').describe().transpose()

model_year                   70           71           72           73  \
mpg          count    29.000000    28.000000    28.000000    40.000000
             mean     17.689655    21.250000    18.714286    17.100000
             std       5.339231     6.591942     5.435529     4.700245
             min       9.000000    12.000000    11.000000    11.000000
             25%      14.000000    15.500000    13.750000    13.000000
             50%      16.000000    19.000000    18.500000    16.000000
             75%      22.000000    27.000000    23.000000    20.000000
             max      27.000000    35.000000    28.000000    29.000000
cylinders    count    29.000000    28.000000    28.000000    40.000000
             mean      6.758621     5.571429     5.821429     6.375000
             std       1.724926     1.665079     2.073708     1.807215
             min       4.000000     4.000000     3.000000     3.000000
             25%       6.000000     4.000000     4.000000     4.000000
             50%       8.000000     6.000000     4.000000     7.000000
             75%       8.000000     6.500000     8.000000     8.000000
             max       8.000000     8.000000     8.000000     8.000000
displacement count    29.000000    28.000000    28.000000    40.000000
             mean    281.413793   209.750000   218.375000   256.875000
             std     124.421380   115.102410   123.781964   121.722085
             min      97.000000    71.000000    70.000000    68.000000
             25%     198.000000    97.750000   109.250000   121.750000
             50%     307.000000   228.500000   131.000000   276.000000
             75%     383.000000   273.000000   326.000000   350.250000
             max     455.000000   400.000000   429.000000   455.000000
weight       count    29.000000    28.000000    28.000000    40.000000
             mean   3372.793103  2995.428571  3237.714286  3419.025000
             std     852.868663  1061.830859   974.520960   974.809133
             min    1835.000000  1613.000000  2100.000000  1867.000000
             25%    2648.000000  2110.750000  2285.500000  2554.500000
             50%    3449.000000  2798.000000  2956.000000  3338.500000
             75%    4312.000000  3603.250000  4169.750000  4247.250000
             max    4732.000000  5140.000000  4633.000000  4997.000000
acceleration count    29.000000    28.000000    28.000000    40.000000
             mean     12.948276    15.142857    15.125000    14.312500
             std       3.330982     2.666171     2.850032     2.754222
             min       8.000000    11.500000    11.000000     9.500000
             25%      10.000000    13.375000    13.375000    12.500000
             50%      12.500000    14.500000    14.500000    14.000000
             75%      15.000000    16.125000    16.625000    16.000000
             max      20.500000    20.500000    23.500000    21.000000
origin       count    29.000000    28.000000    28.000000    40.000000
             mean      1.310345     1.428571     1.535714     1.375000
             std       0.603765     0.741798     0.792658     0.667467
             min       1.000000     1.000000     1.000000     1.000000
             25%       1.000000     1.000000     1.000000     1.000000
             50%       1.000000     1.000000     1.000000     1.000000
             75%       1.000000     2.000000     2.000000     2.000000
             max       3.000000     3.000000     3.000000     3.000000

model_year                   74           75           76           77  \
mpg          count    27.000000    30.000000    34.000000    28.000000
             mean     22.703704    20.266667    21.573529    23.375000
             std       6.420010     4.940566     5.889297     6.675862
             min      13.000000    13.000000    13.000000    15.000000
             25%      16.000000    16.000000    16.750000    17.375000
             50%      24.000000    19.500000    21.000000    21.750000
             75%      27.000000    23.000000    26.375000    30.000000
             max      32.000000    33.000000    33.000000    36.000000
cylinders    count    27.000000    30.000000    34.000000    28.000000
             mean      5.259259     5.600000     5.647059     5.464286
             std       1.583390     1.522249     1.667558     1.815206
             min       4.000000     4.000000     4.000000     3.000000
             25%       4.000000     4.000000     4.000000     4.000000
             50%       4.000000     6.000000     6.000000     4.000000
             75%       6.000000     6.000000     7.500000     8.000000
             max       8.000000     8.000000     8.000000     8.000000
displacement count    27.000000    30.000000    34.000000    28.000000
             mean    171.740741   205.533333   197.794118   191.392857
             std      92.601127    87.669730    94.422256   107.813742
             min      71.000000    90.000000    85.000000    79.000000
             25%      90.000000   121.000000   102.500000    97.750000
             50%     122.000000   228.000000   184.000000   143.000000
             75%     250.000000   250.000000   291.000000   270.500000
             max     350.000000   400.000000   351.000000   400.000000
weight       count    27.000000    30.000000    34.000000    28.000000
             mean   2877.925926  3176.800000  3078.735294  2997.357143
             std     949.308571   765.179781   821.371481   912.825902
             min    1649.000000  1795.000000  1795.000000  1825.000000
             25%    2116.500000  2676.750000  2228.750000  2135.000000
             50%    2489.000000  3098.500000  3171.500000  2747.500000
             75%    3622.500000  3662.250000  3803.750000  3925.000000
             max    4699.000000  4668.000000  4380.000000  4335.000000
acceleration count    27.000000    30.000000    34.000000    28.000000
             mean     16.203704    16.050000    15.941176    15.435714
             std       1.688532     2.471737     2.801419     2.273391
             min      13.500000    11.500000    12.000000    11.100000
             25%      15.250000    14.125000    13.925000    14.000000
             50%      16.000000    16.000000    15.500000    15.650000
             75%      17.000000    17.375000    17.550000    16.925000
             max      21.000000    21.000000    22.200000    19.000000
origin       count    27.000000    30.000000    34.000000    28.000000
             mean      1.666667     1.466667     1.470588     1.571429
             std       0.832050     0.730297     0.706476     0.835711
             min       1.000000     1.000000     1.000000     1.000000
             25%       1.000000     1.000000     1.000000     1.000000
             50%       1.000000     1.000000     1.000000     1.000000
             75%       2.000000     2.000000     2.000000     2.000000
             max       3.000000     3.000000     3.000000     3.000000

model_year                   78           79           80           81  \
mpg          count    36.000000    29.000000    29.000000    29.000000
             mean     24.061111    25.093103    33.696552    30.334483
             std       6.898044     6.794217     7.037983     5.591465
             min      16.200000    15.500000    19.100000    17.600000
             25%      19.350000    19.200000    29.800000    26.600000
             50%      20.700000    23.900000    32.700000    31.600000
             75%      28.000000    31.800000    38.100000    34.400000
             max      43.100000    37.300000    46.600000    39.100000
cylinders    count    36.000000    29.000000    29.000000    29.000000
             mean      5.361111     5.827586     4.137931     4.620690
             std       1.495761     1.774199     0.580895     1.082781
             min       4.000000     4.000000     3.000000     4.000000
             25%       4.000000     4.000000     4.000000     4.000000
             50%       5.500000     6.000000     4.000000     4.000000
             75%       6.000000     8.000000     4.000000     6.000000
             max       8.000000     8.000000     6.000000     8.000000
displacement count    36.000000    29.000000    29.000000    29.000000
             mean    177.805556   206.689655   115.827586   135.310345
             std      76.012713    96.307581    33.744914    58.387929
             min      78.000000    85.000000    70.000000    79.000000
             25%     115.500000   121.000000    90.000000    98.000000
             50%     159.500000   183.000000   107.000000   119.000000
             75%     231.000000   302.000000   140.000000   151.000000
             max     318.000000   360.000000   225.000000   350.000000
weight       count    36.000000    29.000000    29.000000    29.000000
             mean   2861.805556  3055.344828  2436.655172  2522.931034
             std     626.023907   747.881497   432.235491   533.600501
             min    1800.000000  1915.000000  1835.000000  1755.000000
             25%    2282.500000  2556.000000  2110.000000  2065.000000
             50%    2910.000000  3190.000000  2335.000000  2385.000000
             75%    3410.000000  3725.000000  2800.000000  2900.000000
             max    4080.000000  4360.000000  3381.000000  3725.000000
acceleration count    36.000000    29.000000    29.000000    29.000000
             mean     15.805556    15.813793    16.934483    16.306897
             std       2.129915     2.952931     2.826694     2.192509
             min      11.200000    11.300000    11.400000    12.600000
             25%      14.475000    14.000000    15.100000    14.800000
             50%      15.750000    15.000000    16.500000    16.200000
             75%      16.825000    17.300000    18.700000    17.300000
             max      21.500000    24.800000    23.700000    20.700000
origin       count    36.000000    29.000000    29.000000    29.000000
             mean      1.611111     1.275862     2.206897     1.965517
             std       0.837608     0.591400     0.818505     0.944259
             min       1.000000     1.000000     1.000000     1.000000
             25%       1.000000     1.000000     2.000000     1.000000
             50%       1.000000     1.000000     2.000000     2.000000
             75%       2.000000     1.000000     3.000000     3.000000
             max       3.000000     3.000000     3.000000     3.000000

model_year                   82
mpg          count    31.000000
             mean     31.709677
             std       5.392548
             min      22.000000
             25%      27.000000
             50%      32.000000
             75%      36.000000
             max      44.000000
cylinders    count    31.000000
             mean      4.193548
             std       0.601074
             min       4.000000
             25%       4.000000
             50%       4.000000
             75%       4.000000
             max       6.000000
displacement count    31.000000
             mean    128.870968
             std      39.352037
             min      91.000000
             25%     105.000000
             50%     119.000000
             75%     142.000000
             max     262.000000
weight       count    31.000000
             mean   2453.548387
             std     354.276713
             min    1965.000000
             25%    2127.500000
             50%    2525.000000
             75%    2727.500000
             max    3035.000000
acceleration count    31.000000
             mean     16.638710
             std       2.484844
             min      11.600000
             25%      14.850000
             50%      16.400000
             75%      18.000000
             max      24.600000
origin       count    31.000000
             mean      1.645161
             std       0.914636
             min       1.000000
             25%       1.000000
             50%       1.000000
             75%       3.000000
             max       3.000000

In [16]:
year_cyl = df.groupby(['model_year', 'cylinders']).mean()

In [18]:
year_cyl.index.names

FrozenList(['model_year', 'cylinders'])

In [19]:
year_cyl.index.levels

FrozenList([[70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82], [3, 4, 5, 6, 8]])

In [24]:
year_cyl.loc[[70,82]]

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
82         4          1.714286
           6          1.000000

In [25]:
year_cyl.loc[(70, 4)]

mpg               25.285714
displacement     107.000000
weight          2292.571429
acceleration      16.000000
origin             2.285714
Name: (70, 4), dtype: float64